apiVersion: v1

kind: PersistentVolumeClaim

metadata:
  name: cifar10-data
  namespace: mlops-cifar10

spec:
  accessModes:
    - ReadWriteOnce

  resources:
    requests:
      storage: 1Gi

  storageClassName: standard
